# Generated by Django 3.2.5 on 2021-07-21 16:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('password', models.CharField(max_length=50)),
                ('date_registered', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
