# Generated by Django 3.2.5 on 2021-07-22 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.CharField(default='Email', max_length=50),
        ),
    ]
